apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-titiler-middleware
  namespace: {{ .Release.Namespace }}
spec:
  headers:
    accessControlAllowOrigin: "{{ .Values.ui.host }}"
