apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-titiler-middleware-cors
  namespace: {{ .Release.Namespace }}
spec:
  headers:
    accessControlAllowOriginList: 
      - "{{ .Values.ui.host }}"
